name = "survey-platform-api"
type = "service"
main = "src/index.ts"
compatibility_date = "2026-09-26"

[[d1_databases]]
binding = "survey_platform_db"
database_name = "survey-platform-db"
database_id = "67ec687e-78d2-4d8e-a63f-093d731442f8"
